include:
  - ollama-ci.yaml

services:
  backend:
    extends:
      file: compose.yaml
      service: backend
    environment:
      BASE_URL: http://ollama:11434/v1/

  frontend:
    extends:
      file: compose.yaml
      service: frontend
