services:
  backend:
    env_file: 'backend.env'
    build:
      context: .
      target: backend
    ports:
      - '8080:8080'
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.15.0-community
    ports:
      - '7474:7474'  # HTTP
      - '7687:7687'  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial_size=512M
      - NEO4J_server_memory_heap_max_size=1G
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
