services:
  ollama:
    image: ilopezluna/llama3.2:0.5.4-1b #TODO use a Docker Official Image here
    ports:
      - '11434:11434'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'bash',
          '-c',
          "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
